apiVersion: v1
kind: Service
metadata:
  name: db-liquibase-migration-postgres
  labels:
    app: db-liquibase-migration-postgres
spec:
  selector:
    app: db-liquibase-migration-postgres
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP