apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-mongo-migration-migrate-mongo-v1
spec:
  template:
    spec:
      containers:
        - name: db-migrate-mongo-migration-migrate-mongo-v1
          image: example-migrate-mongo-database-migration:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
  backoffLimit: 4

