apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-migrate-mongo-migration-mongodb
  labels:
    app: db-migrate-mongo-migration-mongodb
spec:
  selector:
    matchLabels:
      app: db-migrate-mongo-migration-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: db-migrate-mongo-migration-mongodb
    spec:
      containers:
        - name: db-migrate-mongo-migration-mongodb
          image: mongo:4
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: my_db
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017
              name: db
