apiVersion: v1
kind: Service
metadata:
  name: db-migrate-mongo-migration-mongodb
  labels:
    app: db-migrate-mongo-migration-mongodb
spec:
  selector:
    app: db-migrate-mongo-migration-mongodb
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP